image: acastellano/cirunnerbionic

stages:
    - test
    - build

unit_tests:
    stage: test
    before_script:
        - apt-get update -qq && apt-get install -y gcc make cpanminus libexpat1 expat libexpat1-dev libxml2-dev zlib1g-dev libssl-dev wget
        - echo "deb https://dl.bintray.com/rabbitmq/debian bionic main" > /etc/apt/sources.list.d/bintray.rabbitmq.list
        - echo "deb [ arch=amd64  ] http://repo.daedalus-project.io/ any daedalus" > /etc/apt/sources.list.d/daedalus-project.list
        - wget -O- https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc | apt-key add -
        - wget -O - http://repo.daedalus-project.io/repo.daedalus-project.io.gpg-key.pub | apt-key add -
        - apt-get update
        - apt-get install -y rabbitmq-server libmoose-perl libmoosex-nonmoose-perl libmoosex-strictconstructor-perl libclass-factory-perl libxml-parser-perl  libmodule-pluginfinder-perl libnet-amqp-rabbitmq-perl libxml-libxml-perl libtest-exception-perl libxml-simpleobject-perl libstring-random-perl
        - service rabbitmq-server start
    script:
        - perl --version
        - cd t && cpanm --quiet --installdeps --notest . && cd ..
        - perl Makefile.PL && make && mutator mutate lib/Daedalus/Hermes.pm && mutator mutate lib/Daedalus/Hermes/RabbitMQ.pm && make test && mutator test

run-build:
    stage: build
    artifacts:
        paths:
            - build/*
    script:
        - apt-get update -qq && apt-get install -y gcc make cpanminus libexpat1 expat libexpat1-dev libxml2-dev zlib1g-dev libssl-dev wget
        - echo "deb https://dl.bintray.com/rabbitmq/debian bionic main" > /etc/apt/sources.list.d/bintray.rabbitmq.list
        - echo "deb [ arch=amd64  ] http://repo.daedalus-project.io/ any daedalus" > /etc/apt/sources.list.d/daedalus-project.list
        - wget -O- https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc | apt-key add -
        - wget -O - http://repo.daedalus-project.io/repo.daedalus-project.io.gpg-key.pub | apt-key add -
        - apt-get update
        - apt-get install -y rabbitmq-server libmoose-perl libmoosex-nonmoose-perl libmoosex-strictconstructor-perl libclass-factory-perl libxml-parser-perl  libmodule-pluginfinder-perl libnet-amqp-rabbitmq-perl libxml-libxml-perl libtest-exception-perl libxml-simpleobject-perl libstring-random-perl libtest-most-perl
        - apt-get install -y dh-make-perl dpkg-dev
        - service rabbitmq-server start
        - dpkg-buildpackage -uc -b
        - mkdir build
        - mv ../*.deb build/
