image: acastellano/cirunnerbionic

stages:
    - test

unit_tests:
    stage: test
    before_script:
        - apt-get update -qq && apt-get install -y gcc make cpanminus libexpat1 expat libexpat1-dev libxml2-dev zlib1g-dev libssl-dev
    script:
        - perl --version
        - cpanm --quiet --installdeps --notest .
        - perl Makefile.PL && make && mutator mutate lib/Daedalus/Hermes.pm && mutator mutate lib/Daedalus/Hermes/RabbitMQ.pm && make test && mutator test
