language: perl
perl:
    - '5.26'
    - '5.24'
    - '5.22'
    - '5.20'

before_install:
    - echo "deb https://dl.bintray.com/rabbitmq/debian trusty main" | sudo tee /etc/apt/sources.list.d/bintray.rabbitmq.list
    - wget -O- https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc |  sudo apt-key add -
    - sudo apt-get -qq update
    - wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    - sudo dpkg -i erlang-solutions_1.0_all.deb
    - sudo apt-get update
    - sudo apt-get install esl-erlang=1:19.3.6
    - sudo apt-get install -y rabbitmq-server 

script: perl Makefile.PL && make && make test
after_success:
    - cover -test
    - cover -report codecov
