language: perl
perl:
    - '5.26'
    - '5.24'
    - '5.22'
    - '5.20'

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y rabbitmq-server 

script: perl Makefile.PL && make && make test
after_success:
    - cover -test
    - cover -report codecov
